### ISSUE TITLE
Add SCSSPhp Library Option

### ISSUE THREAD

**Issue by jaswrks** [websharks/css-minifier#1]
See: http://leafo.github.io/scssphp/docs/#output-formatting
~ A fork of: https://github.com/websharks/html-compressor/issues/66

Work on this issue should also correct [this bug](https://github.com/websharks/html-compressor/issues/66) in the WebSharks CSS compression flavor.

```
.test :first-child and .test:first-child
```

**Comment by jaswrks** [comment]
leafo/scssphp not implemented for the following reasons:
- Compressed output format is lacking the compression algorithm found in libsass; i.e., it does not work as I expected it to, given that it is advertised as being an SCSS port for PHP.
- The mild compression that is applied, is output via buffers in PHP, making it incompatible with most use cases found for the HTML Compressor at this time; e.g., inside an output buffer already via ZenCache.

**Comment by jaswrks** [comment]
Bug fixed in CSS Minifier library.

```
.test :first-child and .test:first-child
```

**Comment by jaswrks** [comment]
cc @raamdev

**Comment by lkraav** [comment]
Aren't leafo's projects all but abandoned?

I migrated to https://github.com/sanchothefat/wp-less a long time ago and he also has `wp-sass`.
